spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/buckmoo?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  mvc:
    static-path-pattern: /**

server:
  servlet:
    context-path: /buckmoo


wechat:
  mpAppId: wxb39b42f5fd93c167
  mpAppSecret: 3d63c96f84e4587baa5e4a6f85d1a515
  openAppId:
  openAppSecret:
  mchId: 1545797881
  mchKey: lhl123456anxlhl123456anxlhl12345
  mchPath: D:\develop\wechat_project\apiclient_cert.p12
  notifyUrl: http://tim.natapp1.cc/buckmoo/allpay/notify

projecturl:
  wechatMpAuthorize: http://tim.natapp1.cc
  wechatOpenAuthorize: http://tim.natapp1.cc
  buckmoo: http://tim.natapp1.cc/buckmoo
  imgPath: C:\Users\Tim\Desktop\FileServer
