spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    # password: lhl123456an+
    # url: jdbc:mysql://139.159.234.67:/buckmoo?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    password: 123456
    url: jdbc:mysql://127.0.0.1/buckmoo?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    # password: 123456
    # url: jdbc:mysql://172.16.150.128/buckmoo?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    dbcp2:
      max-idle: 10
      max-wait-millis: 5000
      min-idle: 5
      initial-size: 5
  jpa:
    show-sql: true
    jackson:
      default-property-inclusion: non_null
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    context-path: /buckmoo

wechat:
  mpAppId: wxb39b42f5fd93c167
  mpAppSecret: 3d63c96f84e4587baa5e4a6f85d1a515
  openAppId:
  openAppSecret:
  mchId: 1545797881
  mchKey: lhl123456anxlhl123456anxlhl12345
  mchPath: /Users/tim/develop/wechat_project/apiclient_cert.p12
  notifyUrl: http://tim.natapp1.cc/buckmoo/allpay/notify

projecturl:
  wechatMpAuthorize: http://tim.natapp1.cc
  wechatOpenAuthorize: http://tim.natapp1.cc
  buckmoo: http://tim.natapp1.cc/buckmoo
  imgPath: /Users/tim/Desktop/FileServer